use File::Copy;

if(!$ARGV[0] || !$ARGV[1]) {
	print "\n";
	print "Usage:\n";
	print 'azone_map_generate.pl "C:\everquest_dir" "C:\azone_dir"' . "\n";
	exit;
}

my $everquest_directory = $ARGV[0];
my $azone_directory = $ARGV[1];

load_zones();
convert_zones();
build_result();

my $convert_count = 0;
my $map_count = 0;
my $eqg_count = 0;
my $s3d_count = 0;

sub build_result {
	
	chdir ($azone_directory);
	
	mkdir("azone_generated");
	
	opendir(DIR, $everquest_directory) or die $!;
	while (my $file = readdir(DIR)) {
		$raw_file = $file;
		
		if($file=~/\.map/i){
			$map_count++;
			move($everquest_directory . $file, "azone_generated/" . $file);
		}
	}
	
	print "\n";
	print "################################################\n";
	print "#::: Build Report\n";
	print "################################################\n";
	print "\n";
	print "Built (" . $map_count . ") map files out of total found zone files (" . $convert_count . ")...\n";
	print "Found (" . $s3d_count . ") S3D Maps\n";
	print "Found (" . $eqg_count . ") EQG Maps\n";
	print "Your maps can be found in the 'azone_generated' folder\n";
	print "azone build log can be found in azone.log\n";
}

sub convert_zones {
	
	print "Finding zones...\n";
	
	my $build_files = "";

	opendir(DIR, $everquest_directory) or die $!;
	while (my $file = readdir(DIR)) {
		$raw_file = $file;
		
		if($file=~/.eqg|.s3d/i){
			$file =~ s/.eqg//g;
			$file =~ s/.s3d//g;
			
			if($zones{$file}){
			
				if($raw_file=~/.eqg/i){ $eqg_count++; }
				if($raw_file=~/.s3d/i){ $s3d_count++; }
				
				$build_files .= " " . $file;
				
				$convert_count++;
			}
		}
	}

	chdir ($everquest_directory);

	print "Found (" . $convert_count . ") maps to generate... Building...\n";
	
	print `./azone $build_files > nul`;
}

sub load_zones {

	%zones = (
		"abysmal", => 1,
		"acrylia", => 1,
		"airplane", => 1,
		"akanon", => 1,
		"akheva", => 1,
		"anguish", => 1,
		"apprentice", => 1,
		"arcstone", => 1,
		"arena", => 1,
		"arena2", => 1,
		"arttest", => 1,
		"ashengate", => 1,
		"atiiki", => 1,
		"aviak", => 1,
		"barindu", => 1,
		"barren", => 1,
		"barter", => 1,
		"bazaar", => 1,
		"befallen", => 1,
		"befallenb", => 1,
		"beholder", => 1,
		"bertoxtemple", => 1,
		"blackburrow", => 1,
		"blacksail", => 1,
		"bloodfields", => 1,
		"bloodmoon", => 1,
		"bothunder", => 1,
		"broodlands", => 1,
		"buriedsea", => 1,
		"burningwood", => 1,
		"butcher", => 1,
		"cabeast", => 1,
		"cabwest", => 1,
		"cauldron", => 1,
		"causeway", => 1,
		"cazicthule", => 1,
		"chambersa", => 1,
		"chambersb", => 1,
		"chambersc", => 1,
		"chambersd", => 1,
		"chamberse", => 1,
		"chambersf", => 1,
		"charasis", => 1,
		"chardok", => 1,
		"chardokb", => 1,
		"citymist", => 1,
		"clz", => 1,
		"cobaltscar", => 1,
		"codecay", => 1,
		"commonlands", => 1,
		"commons", => 1,
		"corathus", => 1,
		"corathusa", => 1,
		"corathusb", => 1,
		"crescent", => 1,
		"crushbone", => 1,
		"cryptofshade", => 1,
		"crystal", => 1,
		"crystallos", => 1,
		"cshome", => 1,
		"dalnir", => 1,
		"dawnshroud", => 1,
		"deadbone", => 1,
		"delvea", => 1,
		"delveb", => 1,
		"devastationa", => 1,
		"devastation", => 1,
		"direwind", => 1,
		"discord", => 1,
		"discordtower", => 1,
		"drachnidhive", => 1,
		"drachnidhivea", => 1,
		"drachnidhiveb", => 1,
		"drachnidhivec", => 1,
		"dragonscale", => 1,
		"dragonscaleb", => 1,
		"dranik", => 1,
		"dranikcatacombsa", => 1,
		"dranikcatacombsb", => 1,
		"dranikcatacombsc", => 1,
		"dranikhollowsa", => 1,
		"dranikhollowsb", => 1,
		"dranikhollowsc", => 1,
		"draniksewersa", => 1,
		"draniksewersb", => 1,
		"draniksewersc", => 1,
		"draniksscar", => 1,
		"dreadlands", => 1,
		"dreadspire", => 1,
		"droga", => 1,
		"dulak", => 1,
		"eastkarana", => 1,
		"eastkorlach", => 1,
		"eastkorlacha", => 1,
		"eastwastes", => 1,
		"echo", => 1,
		"ecommons", => 1,
		"elddar", => 1,
		"elddara", => 1,
		"emeraldjungle", => 1,
		"erudnext", => 1,
		"erudnint", => 1,
		"erudsxing", => 1,
		"erudsxing2", => 1,
		"everfrost", => 1,
		"fearplane", => 1,
		"feerrott", => 1,
		"felwithea", => 1,
		"felwitheb", => 1,
		"ferubi", => 1,
		"fhalls", => 1,
		"fieldofbone", => 1,
		"firiona", => 1,
		"freeportacademy", => 1,
		"freeportarena", => 1,
		"freeportcityhall", => 1,
		"freeporteast", => 1,
		"freeporthall", => 1,
		"freeportmilitia", => 1,
		"freeportsewers", => 1,
		"freeporttemple", => 1,
		"freeporttheater", => 1,
		"freeportwest", => 1,
		"freporte", => 1,
		"freportn", => 1,
		"freportw", => 1,
		"frontiermtns", => 1,
		"frostcrypt", => 1,
		"frozenshadow", => 1,
		"fungusgrove", => 1,
		"gfaydark", => 1,
		"greatdivide", => 1,
		"griegsend", => 1,
		"grimling", => 1,
		"grobb", => 1,
		"growthplane", => 1,
		"guardian", => 1,
		"guildhall", => 1,
		"guildlobby", => 1,
		"guka", => 1,
		"gukb", => 1,
		"gukbottom", => 1,
		"gukc", => 1,
		"gukd", => 1,
		"guke", => 1,
		"gukf", => 1,
		"gukg", => 1,
		"gukh", => 1,
		"guktop", => 1,
		"gunthak", => 1,
		"gyrospireb", => 1,
		"gyrospirez", => 1,
		"halas", => 1,
		"harbingers", => 1,
		"hateplane", => 1,
		"hateplaneb", => 1,
		"hatesfury", => 1,
		"highkeep", => 1,
		"highpass", => 1,
		"highpasshold", => 1,
		"highpasskeep", => 1,
		"hillsofshade", => 1,
		"hohonora", => 1,
		"hohonorb", => 1,
		"hole", => 1,
		"hollowshade", => 1,
		"iceclad", => 1,
		"icefall", => 1,
		"ikkinz", => 1,
		"illsalin", => 1,
		"illsalina", => 1,
		"illsalinb", => 1,
		"illsalinc", => 1,
		"inktuta", => 1,
		"innothule", => 1,
		"innothuleb", => 1,
		"jaggedpine", => 1,
		"jardelshook", => 1,
		"kael", => 1,
		"kaesora", => 1,
		"kaladima", => 1,
		"kaladimb", => 1,
		"karnor", => 1,
		"katta", => 1,
		"kattacastrum", => 1,
		"kedge", => 1,
		"kerraridge", => 1,
		"kithforest", => 1,
		"kithicor", => 1,
		"kodtaz", => 1,
		"korascian", => 1,
		"kurn", => 1,
		"lakeofillomen", => 1,
		"lakerathe", => 1,
		"lavastorm", => 1,
		"letalis", => 1,
		"lfaydark", => 1,
		"load", => 1,
		"load2", => 1,
		"lopingplains", => 1,
		"maiden", => 1,
		"maidensgrave", => 1,
		"mansion", => 1,
		"mechanotus", => 1,
		"mesa", => 1,
		"mira", => 1,
		"mirb", => 1,
		"mirc", => 1,
		"mird", => 1,
		"mire", => 1,
		"mirf", => 1,
		"mirg", => 1,
		"mirh", => 1,
		"miri", => 1,
		"mirj", => 1,
		"mischiefplane", => 1,
		"mistmoore", => 1,
		"misty", => 1,
		"mistythicket", => 1,
		"mmca", => 1,
		"mmcb", => 1,
		"mmcc", => 1,
		"mmcd", => 1,
		"mmce", => 1,
		"mmcf", => 1,
		"mmcg", => 1,
		"mmch", => 1,
		"mmci", => 1,
		"mmcj", => 1,
		"monkeyrock", => 1,
		"moors", => 1,
		"mseru", => 1,
		"nadox", => 1,
		"najena", => 1,
		"natimbi", => 1,
		"necropolis", => 1,
		"nedaria", => 1,
		"nektropos", => 1,
		"nektulos", => 1,
		"nektulosa", => 1,
		"neriaka", => 1,
		"neriakb", => 1,
		"neriakc", => 1,
		"neriakd", => 1,
		"netherbian", => 1,
		"nexus", => 1,
		"nightmareb", => 1,
		"northkarana", => 1,
		"northro", => 1,
		"nro", => 1,
		"nurga", => 1,
		"oasis", => 1,
		"oceangreenhills", => 1,
		"oceangreenvillage", => 1,
		"oceanoftears", => 1,
		"oggok", => 1,
		"oldblackburrow", => 1,
		"oldbloodfield", => 1,
		"oldcommons", => 1,
		"olddranik", => 1,
		"oldfieldofbone", => 1,
		"oldhighpass", => 1,
		"oldkaesoraa", => 1,
		"oldkaesorab", => 1,
		"oldkithicor", => 1,
		"oldkurn", => 1,
		"oot", => 1,
		"overthere", => 1,
		"paineel", => 1,
		"paludal", => 1,
		"paw", => 1,
		"permafrost", => 1,
		"poair", => 1,
		"podisease", => 1,
		"poeartha", => 1,
		"poearthb", => 1,
		"pofire", => 1,
		"poinnovation", => 1,
		"pojustice", => 1,
		"poknowledge", => 1,
		"ponightmare", => 1,
		"postorms", => 1,
		"potactics", => 1,
		"potimea", => 1,
		"potimeb", => 1,
		"potorment", => 1,
		"potranquility", => 1,
		"povalor", => 1,
		"powar", => 1,
		"powater", => 1,
		"precipiceofwar", => 1,
		"provinggrounds", => 1,
		"qcat", => 1,
		"qey2hh1", => 1,
		"qeynos", => 1,
		"qeynos2", => 1,
		"qeytoqrg", => 1,
		"qinimi", => 1,
		"qrg", => 1,
		"qvic", => 1,
		"qvicb", => 1,
		"rage", => 1,
		"ragea", => 1,
		"rathechamber", => 1,
		"rathemtn", => 1,
		"redfeather", => 1,
		"relic", => 1,
		"riftseekers", => 1,
		"rivervale", => 1,
		"riwwi", => 1,
		"roost", => 1,
		"ruja", => 1,
		"rujb", => 1,
		"rujc", => 1,
		"rujd", => 1,
		"ruje", => 1,
		"rujf", => 1,
		"rujg", => 1,
		"rujh", => 1,
		"ruji", => 1,
		"rujj", => 1,
		"runnyeye", => 1,
		"scarlet", => 1,
		"sebilis", => 1,
		"shadeweaver", => 1,
		"shadowhaven", => 1,
		"shadowrest", => 1,
		"shadowspine", => 1,
		"sharvahl", => 1,
		"shipmvm", => 1,
		"shipmvp", => 1,
		"shipmvu", => 1,
		"shippvu", => 1,
		"shipuvu", => 1,
		"shipworkshop", => 1,
		"silyssar", => 1,
		"sirens", => 1,
		"skyfire", => 1,
		"skylance", => 1,
		"skyshrine", => 1,
		"sleeper", => 1,
		"sncrematory", => 1,
		"snlair", => 1,
		"snplant", => 1,
		"snpool", => 1,
		"soldunga", => 1,
		"soldungb", => 1,
		"soldungc", => 1,
		"solrotower", => 1,
		"soltemple", => 1,
		"solteris", => 1,
		"southkarana", => 1,
		"southro", => 1,
		"sro", => 1,
		"sseru", => 1,
		"ssratemple", => 1,
		"steamfactory", => 1,
		"steamfont", => 1,
		"steamfontmts", => 1,
		"steppes", => 1,
		"stillmoona", => 1,
		"stillmoonb", => 1,
		"stonebrunt", => 1,
		"stonehive", => 1,
		"suncrest", => 1,
		"sunderock", => 1,
		"swampofnohope", => 1,
		"tacvi", => 1,
		"taka", => 1,
		"takb", => 1,
		"takc", => 1,
		"takd", => 1,
		"take", => 1,
		"takf", => 1,
		"takg", => 1,
		"takh", => 1,
		"taki", => 1,
		"takishruins", => 1,
		"takishruinsa", => 1,
		"takj", => 1,
		"templeveeshan", => 1,
		"tenebrous", => 1,
		"thalassius", => 1,
		"theater", => 1,
		"theatera", => 1,
		"thedeep", => 1,
		"thegrey", => 1,
		"thenest", => 1,
		"thevoida", => 1,
		"thevoidb", => 1,
		"thevoidc", => 1,
		"thevoidd", => 1,
		"thevoide", => 1,
		"thevoidf", => 1,
		"thevoidg", => 1,
		"thundercrest", => 1,
		"thurgadina", => 1,
		"thurgadinb", => 1,
		"timorous", => 1,
		"tipt", => 1,
		"torgiran", => 1,
		"toskirakk", => 1,
		"tox", => 1,
		"toxxulia", => 1,
		"trakanon", => 1,
		"tutorial", => 1,
		"tutoriala", => 1,
		"tutorialb", => 1,
		"twilight", => 1,
		"txevu", => 1,
		"umbral", => 1,
		"unrest", => 1,
		"uqua", => 1,
		"valdeholm", => 1,
		"veeshan", => 1,
		"veksar", => 1,
		"velketor", => 1,
		"vergalid", => 1,
		"vexthal", => 1,
		"vxed", => 1,
		"wakening", => 1,
		"wallofslaughter", => 1,
		"warrens", => 1,
		"warslikswood", => 1,
		"westkorlach", => 1,
		"westkorlacha", => 1,
		"westkorlachb", => 1,
		"westkorlachc", => 1,
		"westwastes", => 1,
		"yxtta", => 1,
		"zhisza", => 1,
		"nektulos", => 1,
		"brellsrest", => 1,
		"coolingchamber", => 1,
		"pellucid", => 1,
		"arthicrex", => 1,
		"foundation", => 1,
		"underquarry", => 1,
		"brellsarena", => 1,
		"stonesnake", => 1,
		"convorteum", => 1,
		"thulelibrary", => 1,
		"morellcastle", => 1,
		"alkabormare", => 1,
		"fallen", => 1,
		"feerrott2", => 1,
		"housegarden", => 1,
		"miragulmare", => 1,
		"somnium", => 1,
		"thuledream", => 1,
		"thulehouse1", => 1,
		"thulehouse2", => 1,
		"well", => 1,
		"neighborhood", => 1,
		"argath", => 1,
		"arelis", => 1,
		"sarithcity", => 1,
		"rubak", => 1,
		"beastdomain", => 1,
		"resplendent", => 1,
		"pillarsalra", => 1,
		"windsong", => 1,
		"cityofbronze", => 1,
		"sepulcher", => 1,
		"eastsepulcher", => 1,
		"westsepulcher", => 1,
		"weddingchapel", => 1,
		"weddingchapeldark", => 1,
		"dragoncrypt", => 1,
		"bazaar", => 1,
		"brellstemple", => 1,
		"fungalforest", => 1,
		"lichencreep", => 1,
		"shiningcity", => 1,
		"skyshrine", => 1,
		"breedinggrounds", => 1,
		"chapterhouse", => 1,
		"crystalshard", => 1,
		"eastwastesshard", => 1,
		"eviltree", => 1,
		"grelleth"
	);

}
